### ISSUE TITLE
docs(meta): Add information about S3 config, URL generation, and redirects

### ISSUE THREAD

**Issue by afolson** [swimos/swimos-docs#136]
**Is your request related to a problem? Please describe.**
Only a handful of people know how to set up URLs and redirects to work on S3 so it should be documented :)

**What information would you expect to see in this new document?**

- [ ] Locations and explanations of config files for S3 and Jekyll
- [ ] Information about absolute and relative URLs, when to use each and how
- [ ] How to add redirects TO and FROM pages, when to use which
- [ ] Information on staging environment, gotchas between running Jekyll locally and running it on S3
